

class Urls:
    HOST = "https://demoqa.com"
    TEXT_BOX = f"{HOST}/text-box"
    CHECK_BOX = f"{HOST}/checkbox"
    RADIO_BUTTON = f"{HOST}/radio-button"
    WEB_TABLES = f"{HOST}/webtables"
    BUTTONS = f"{HOST}/buttons"
    LINKS = f"{HOST}/links"
    BROKEN_LINKS_IMAGES = f"{HOST}/broken"
    UPLOAD_FILES = f"{HOST}/upload-download"
    DYNAMIC_PROPERTIES = f"{HOST}/dynamic-properties"
    PRACTICE_FORM = f"{HOST}/automation-practice-form"
    BROWSER_WINDOWS = f"{HOST}/browser-windows"
    ALERTS = f"{HOST}/alerts"
    FRAMES = f"{HOST}/frames"
    ACCORDIAN = f"{HOST}/accordian"
    AUTO_COMPLETE = f"{HOST}/auto-complete"
    DATE_PICKER = f"{HOST}/date-picker"
    SLIDER = f"{HOST}/slider"
    PROGRESS_BAR = f"{HOST}/progress-bar"
    TABS = f"{HOST}/tabs"